language: node_js
# travis runs 'npm install' and 'npm test'
node_js:
- '6'

script:
- npm run test
- bash e2e.sh

after_success:
- bash deploy.sh

cache:
  directories:
  - node_modules

# Travis needs the token to push to github gh-pages
env:
  global:
    secure: YkfVJwqX01gHKtCxTYi1wvHRAdHYvolUAO6bHfqc5HRzLKFh+xygDLez6fws+BufqDphWBjK5TKdL/HJMWyDB2MxglPcrKkdH7ZTVBXQwldRlGIGkCOlsFXyask7/XTlGP3SWPRiZFJmKI4UNMHknNJuWaujSMs7seQ81fZugY3OyVkuBym/Ld0wKX8DedDj6qy+iEwlMkss8NvVndmr3CSbxqJwiPEWC/W7tx7rNbZ8/i3nGG6DNZmIgH4V+XgolhlrtjkWA0O+q6EaAiLfbNDGvbUZg5TRh37IIkAqA40A3IJHSPN9ayLZikGqlQEd675yyVIEi9AUNeQo0cDAVNeVocPVTZXGQscpb6RUx7Z9KbtCYsRSPvc4ZzVLucJhP/QaKqZK39JuSCt1OCiXZjWjZ/k/TXMw4eO+IuOIbroaGFBUF4Hm2X4xq1kA9k9FpR7QFY6PKWj41uf7tcr4xB0CzV/DHFLRpkEoMqboaBWPZBY7l9/u6eCZZLjs2j8f+uQe0r8kGxwIg5BnK5GX50DGUlJ4R34bkt5gj9fsqta0QpZBWh/0/oXd4tL5qxfppXkONMRyfhpLPDm6vtDpw0aWEh/6D/Mjii2G+YyhUA7ThlWC+/roEB1kABlM/f3YnB8EGcPQlLaANhkJjPX9t4XvdAcEBJB/kNse8/vZd60=
