language: node_js
node_js:
- '6'

script:
- ./node_modules/.bin/webdriver-manager update --standalone
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

- nohup bash -c "./node_modules/.bin/webdriver-manager --standalone start 2>&1 &"
- sleep 5
- cat nohup.out

- nohup bash -c "npm run dev 2>&1 &"
- sleep 5
- cat nohup.out

- npm test

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master"
#- npm run cover
- npm test --coverage
- ./node_modules/.bin/codecov
- mkdir -p _site
#- curl -sSf https://static.rust-lang.org/rustup.sh | sh
#- curl -L https://github.com/yihui/ubuntu-bin/releases/download/latest/pandoc.tar.gz | tar zx
#- pandoc -o _site/index.html README.md
#- cp -r img _site
- cp -R app _site/
- cp index.html _site/
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- bash deploy.sh

cache:
  directories:
  - node_modules 
