language: node_js
# travis runs 'npm install' and 'npm test'
node_js:
- '6'
# webdriver-manager is not compatible with node_js 4

before_script:
- "./node_modules/.bin/webdriver-manager update --standalone"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- nohup bash -c "./node_modules/.bin/webdriver-manager --standalone start 2>&1 &"
- sleep 5
- cat nohup.out
- npm instrument
- nohup bash -c "npm run dev 2>&1 &"
- sleep 5
- cat nohup.out

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master"
- npm test --coverage
- "./node_modules/.bin/codecov"
- mkdir -p _site
- cp -R app _site/
- cp index.html _site/
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- bash deploy.sh

cache:
  directories:
  - node_modules

# Travis needs the token to push to github gh-pages
env:
  global:
    secure: YkfVJwqX01gHKtCxTYi1wvHRAdHYvolUAO6bHfqc5HRzLKFh+xygDLez6fws+BufqDphWBjK5TKdL/HJMWyDB2MxglPcrKkdH7ZTVBXQwldRlGIGkCOlsFXyask7/XTlGP3SWPRiZFJmKI4UNMHknNJuWaujSMs7seQ81fZugY3OyVkuBym/Ld0wKX8DedDj6qy+iEwlMkss8NvVndmr3CSbxqJwiPEWC/W7tx7rNbZ8/i3nGG6DNZmIgH4V+XgolhlrtjkWA0O+q6EaAiLfbNDGvbUZg5TRh37IIkAqA40A3IJHSPN9ayLZikGqlQEd675yyVIEi9AUNeQo0cDAVNeVocPVTZXGQscpb6RUx7Z9KbtCYsRSPvc4ZzVLucJhP/QaKqZK39JuSCt1OCiXZjWjZ/k/TXMw4eO+IuOIbroaGFBUF4Hm2X4xq1kA9k9FpR7QFY6PKWj41uf7tcr4xB0CzV/DHFLRpkEoMqboaBWPZBY7l9/u6eCZZLjs2j8f+uQe0r8kGxwIg5BnK5GX50DGUlJ4R34bkt5gj9fsqta0QpZBWh/0/oXd4tL5qxfppXkONMRyfhpLPDm6vtDpw0aWEh/6D/Mjii2G+YyhUA7ThlWC+/roEB1kABlM/f3YnB8EGcPQlLaANhkJjPX9t4XvdAcEBJB/kNse8/vZd60=
